### PR TITLE
Add Bolognesi-2022-Specificity

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
Based on #189.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@xrotwang I get the following error message when I try to download or map the dataset with `norare map Bolognesi-2022-Specificity`. The error remains after reinstalling `pynorare`. Did I forget to add/update anything else?  
```  
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/dsv.py", line 135, in __enter__
    self.f = io.open(self.f, mode='rt', encoding=self.encoding, newline=self.newline or '')
FileNotFoundError: [Errno 2] No such file or directory: 'concept_set_meta.tsv'
```

**Review by LinguList — APPROVED** [review]

**Comment by LinguList** [comment]
I think you must specify the norare folder?

**Comment by AnnikaTjuka** [comment]
Ah ok, I tried that, but it still asks for the `concept_set_meta` files that we renamed to `datasets`.

**Comment by xrotwang** [comment]
@AnnikaTjuka can you paste the complete stack trace?

**Comment by AnnikaTjuka** [comment]
Sure. After using the `--norarepo` argument the error looks like this:
```
INFO    norare at /Users/tjuka/GitHub/Repos/concepticon/concepticon-data
Traceback (most recent call last):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/bin/norare", line 8, in <module>
    sys.exit(main())
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/__main__.py", line 55, in main
    return args.main(args) or 0
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/commands/download.py", line 12, in run
    for dataset in iter_datasets(args):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/cli_util.py", line 16, in iter_datasets
    cls = get_dataset_cls(args.api.datasets[dsid].path.parent)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/dataset.py", line 18, in get_dataset_cls
    mod = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'concept_set_meta/Bolognesi-2022-Specificity/map.py'
```

**Comment by xrotwang** [comment]
@AnnikaTjuka just pushed a fix that makes this work for me. Can you confirm?

**Comment by AnnikaTjuka** [comment]
@xrotwang The last part disappeared but the error with the missing `concept_set_meta` file remains:
```
Traceback (most recent call last):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/bin/norare", line 8, in <module>
    sys.exit(main())
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/__main__.py", line 52, in main
    args.api = NoRaRe(args.norarepo, concepticon=args.repos)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/api.py", line 126, in __init__
    for row in reader(self.repos / 'concept_set_meta.tsv', delimiter='\t', dicts=True):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/dsv.py", line 276, in iterrows
    with _reader(lines_or_file, encoding=encoding, **kw) as r:
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/dsv.py", line 135, in __enter__
    self.f = io.open(self.f, mode='rt', encoding=self.encoding, newline=self.newline or '')
FileNotFoundError: [Errno 2] No such file or directory: 'concept_set_meta.tsv'
```
I also added the norare-data repository as a clone to my `catalog.ini` file.

**Comment by xrotwang** [comment]
What version of pynorare are you running?
```python
>>> import pynorare
RDFLib Version: 5.0.0
>>> pynorare.__version__
'1.0.1.dev0'
```

**Comment by AnnikaTjuka** [comment]
I just updated to version `1.0.1.dev0` but now the error looks like this:
```
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/bin/norare", line 11, in <module>
    load_entry_point('pynorare==1.0.1.dev0', 'console_scripts', 'norare')()
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare-1.0.1.dev0-py3.8.egg/pynorare/__init__.py", line 1, in <module>
    from pynorare.api import *  # noqa: F401, F403
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare-1.0.1.dev0-py3.8.egg/pynorare/api.py", line 12, in <module>
    from csvw.metadata import TableGroup
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw-3.1.1-py3.8.egg/csvw/__init__.py", line 3, in <module>
    from .metadata import (
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw-3.1.1-py3.8.egg/csvw/metadata.py", line 32, in <module>
    from .datatypes import DATATYPES
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw-3.1.1-py3.8.egg/csvw/datatypes.py", line 27, in <module>
    import jsonschema
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/jsonschema/__init__.py", line 34, in <module>
    __version__ = metadata.version("jsonschema")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 531, in version
    return distribution(distribution_name).version
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 236, in version
    return self.metadata['Version']
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 224, in metadata
    self.read_text('METADATA')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 491, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Comment by xrotwang** [comment]
And what command are you running? `norare map datasets/Bolognesi-2022-Specificity`?

**Comment by AnnikaTjuka** [comment]
I tried `norare map datasets/Bolognesi-2022-Specificity` and `norare map Bolognesi-2022-Specificity` which both lead to the same error. I think I need to set up a new environment from scratch and I might also check if there are legacy items in my repository. I'll post an update tomorrow at the latest.

**Comment by AnnikaTjuka** [comment]
@xrotwang A new day (and a new virtual environment) make your troubles go away. Everything is working again!

**Comment by AnnikaTjuka** [comment]
Oh no, that's the big league of troubles. I'm not sure my advice works here. But fingers crossed!

**Pull request merged**
