### PR TITLE
Add Multi-SimLex

### PR DESCRIPTION
**Pull request by AnnikaTjuka**

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
The scores and translations are offered in separate files. That's why I had to merge the two files. I also duplicated each line to represent the words of the pairs, similar to the SimLex999 data in Concepticon. Thus, the workflow differed slightly from the other data sets, but the result is a cool multilingual data set :)

**Review by LinguList — COMMENTED** [review]
This looks very nice. Given the multitude of languages, I was asking myself, if it is worthwhile to check those concepts and add them, albeit that they are not fully covered to concepticon instead? Remember that this would also increase support for new data to be mapped (e.g., arabic!).

**Comment by AnnikaTjuka** [comment]
Yes, I also thought about mapping the whole list by hand and add it to Concepticon, but 3,776 words would take me at least 2-3 weeks. Using the automatically mapped list in this PR, check the remaining 894, and add the list to Concepticon would be another workflow. Is this something that we would need to integrate into the paper? Or can we take it as an exception?

**Comment by LinguList** [comment]
Well, this semi-automated workflow that adds multi-simlex to concepticon 
sounds in fact also reasonable. We can afford not to link too many items 
there for now, and later do more!

**Comment by AnnikaTjuka** [comment]
Ok, then I'll close this PR and add the list to Concepticon. Does it make sense to use the automated mapping, check it, and still add the whole list (with most of the items left unmapped)? This would allow us to add more mappings later on.

**Comment by LinguList** [comment]
That's what I thought, yes!

**Comment by AnnikaTjuka** [comment]
Great, will do!

**Pull request closed without merging**
