### PR TITLE
add jackson 2019

### PR DESCRIPTION
**Pull request by LinguList**
@AnnikaTjuka, could you please check if I did all correctly with this dataset on emotion word ratings by Jackson et al?

### CODE REVIEW

**Comment by LinguList** [comment]
And don't be shy in criticizing, as I need to learn to contribute more regularly!

**Review by AnnikaTjuka — COMMENTED** [review]
Just a few comments.

**Comment by LinguList** [comment]
Thanks, I hope I addressed all points now.

**Review by AnnikaTjuka — APPROVED** [review]
Yes, looks good!

**Pull request merged**
