### PR TITLE
Update Website

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
This PR updates the https://digling.org/norare/.

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
I do not exactly understand why the app/concepticon.js was changed. There is a full function missing. Did you do that on purpose, @AnnikaTjuka, or did I forget to update something here, etc.?

**Comment by LinguList** [comment]
Yes, it breaks the app, (you can check yourself, the app does no longer show the data). So the modification on the file should not be done...

**Comment by AnnikaTjuka** [comment]
Ah, I'll restore it then.

**Comment by LinguList** [comment]
This is a bit tricky: concepticon.js is in app/data/ and in app/, one is 
just the code to browse also through metadata with norare, this is 
app/concepticon.js and should not be changed, the other one in data/ 
should be changed. So by adding the concepticon.js to app/concepticon.js 
you disabled the norare app (this must be reverted).

**Comment by AnnikaTjuka** [comment]
Ok, now I see.

**Comment by AnnikaTjuka** [comment]
I updated the data/concepticon.js file.

**Comment by AnnikaTjuka** [comment]
The app shows the data again, so I'll merge.

**Pull request merged**
