### PR TITLE
Add NoRaRe printed

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
This PR updates the NoRaRe web app and the README.md with the reference to the printed version of the article.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
@LinguList Could you update the online version?

**Comment by AnnikaTjuka** [comment]
Pinging @LinguList. Not sure if you had time to check the PR yesterday.

**Comment by LinguList** [comment]
Did not, of course, sorry.

**Review by LinguList — APPROVED** [review]
I'd then try and upload the app today.

**Comment by AnnikaTjuka** [comment]
Great, many thanks!

**Pull request merged**
