### PR TITLE
Add SUBTLEX-UK

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
This PR adds the SUBTLEX-UK data.

### CODE REVIEW

**Comment by AnnikaTjuka** [comment]
I tested the data as usual, but received an error `norare stats`:

<details><summary>error message</summary>
<p>
```
INFO    analyze VanHeuven-2014-Frequency
Traceback (most recent call last):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/datatypes.py", line 323, in to_python
    return _decimal.Decimal(v)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 696, in iterdicts
    res[col.header] = col.read(v)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 414, in read
    return datatype.read(v)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 326, in read
    return self.validate(self.parse(v))
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 303, in parse
    return self.basetype.to_python(v, **self.derived_description)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/datatypes.py", line 351, in to_python
    return int(decimal.to_python(v, **kw))
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/datatypes.py", line 325, in to_python
    decimal.value_error(v)
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/datatypes.py", line 40, in value_error
    raise ValueError('invalid lexical value for {}: {}'.format(cls.name, v))
ValueError: invalid lexical value for decimal: NA

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/bin/norare", line 8, in <module>
    sys.exit(main())
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/__main__.py", line 55, in main
    return args.main(args) or 0
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/commands/stats.py", line 23, in run
    for cid, concept in ds.concepts.items():
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/pynorare/api.py", line 54, in concepts
    for row in self.table:
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 698, in iterdicts
    log_or_raise(
  File "/Users/tjuka/GitHub/VirtualEnv/base-env/lib/python3.8/site-packages/csvw/metadata.py", line 48, in log_or_raise
    raise exception_cls(msg)
ValueError: concept_set_meta/VanHeuven-2014-Frequency/VanHeuven-2014-Frequency.tsv:48:5 ENGLISH_FREQUENCY_CBEEBIES: invalid lexical value for decimal: NA
```
</p>

</details>

**Comment by AnnikaTjuka** [comment]
In the former version of pynorare the `NA` values were integrated into the `types.py`,  but this file was deleted. 
@LinguList @xrotwang Is there a way to handle the `NA` values in the dataset? Should I open an issue in pynorare?

**Comment by AnnikaTjuka** [comment]
Thanks for your suggestion, @LinguList! It worked and `norare stats` runs without an error now!

**Comment by LinguList** [comment]
yep, so feel free to merge now ;)

**Pull request merged**
