### PR TITLE
Update norare.tsv

### PR DESCRIPTION
**Pull request by AnnikaTjuka**
This PR adds the columns from several ranked lists and the newly added lists from Concepticon to norare.tsv. In addition, I added the files to prepare the Databases of Paradigmatic Semantic Relation Pairs.

Everything was checked with `norare stats` and `norare check`.

### CODE REVIEW

**Review by LinguList — APPROVED** [review]
very nice, we should soon re-run the python-app command, to also update the webiste at digling.org/norare/

**Comment by LinguList** [comment]
Turns out, third-tone pinyin is not marked in the pinyin, you have cases like jiǎojiǎo, which should be jiáojiǎo. So it is consistent with the source. Adding pinyin would represent this case as `ts j au ³⁵/²¹⁴ + ts j au ²¹⁴`.

**Comment by AnnikaTjuka** [comment]
I re-run `norare app` and the website now lists all 98(!!) data sets.

I don't follow the second comment:

> Turns out, third-tone pinyin is not marked in the pinyin, you have cases like jiǎojiǎo, which should be jiáojiǎo. So it is consistent with the source. Adding pinyin would represent this case as `ts j au ³⁵/²¹⁴ + ts j au ²¹⁴`.

**Comment by LinguList** [comment]
wrong thread !!!

**Comment by AnnikaTjuka** [comment]
Ah, ok :) I'll merge then.

**Pull request merged**
